### ISSUE TITLE
WE schema import limitations

### ISSUE THREAD

**Issue by BuckarooBanzay** [blockexchange/blockexchange_server#620]
@Ygarr (sorry, i have no idea how to reach out to you another way :P)

I saw you uploaded a few schematics, did you have some issues with the WE import mechanism?
I'm interested in feedback for that one, i tested it a bit and had some issues with the lua stack/table limit, did you get to the "25550 node limit" error or was every we-file below that?

**Comment by Ygarr** [comment]
It`s ok.
Yes, one of files seems was too big(some scheme from Karsthafen).
Just checked it`s 222 Mb

All files from this mod was uploaded successfully. https://content.minetest.net/packages/Thunder1035/the_build_spawner/ 

But others (including for example from this modhttps://github.com/cornernote/minetest-towntest/tree/master/towntest_chest/buildings )
just show upload error. Do not why, but think that`s because of unique non-standard mod nodes or smth else.

TBH, most of files I have are in mts format that`s question....

**Comment by MrRar** [comment]
I checked https://github.com/cornernote/minetest-towntest/tree/master/towntest_chest/buildings
That repo has WorldEdit version 3 files which are very different from WE 4 and 5.

**Comment by BuckarooBanzay** [comment]
> the "25550 node limit" error or was every we-file below that?

fixed with 75c1402ea21baaa9f5b219fb9f8b8c75fd442db3 and 272a318246cead93232890add6f7f007700cd906
